# Generated by Django 5.2 on 2025-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_class',
            field=models.CharField(choices=[('Morning A', 'Morning A'), ('Morning B', 'Morning B'), ('Morning C', 'Morning C')], default='Morning B', max_length=20),
        ),
    ]
